Makefile, src/backend/funmooc/settings.py
Some settings have changed on Richie master that are breaking this repository (breaking changes are not taken care of as we are not yet in v1.0.0).
Apply the same changes as what was done in Richie:
- the `FUN_PLUGINS_GROUP` setting was renamed to `RICHIE_PLUGINS_GROUP`
- the `single-column.html` template was renamed to `single_column.html`
- the `fullwidth.html` template is kept only as a base template but can't be used anymore to build pages,
- the `create_demo_site` does not do its database partial cleaning anymore. We now rely on the `flush` Django command.
=> 🐛(settings) fix settings following changes on Richie master

.circleci/config.yml, Makefile, README.md, docker-compose.yml, env.d/production, requirements/base.txt
We need a way to automate Docker production image build, validation & publication.
Add base CircleCI workflow to:
=> Add base Continuous Integration pipeline

.circleci/config.yml
Environment variables required for our tagging strategy are empty.
=> 🐛(circleci) fix hub publication job

CHANGELOG.md, requirements/base.txt, src/frontend/package.json, src/frontend/yarn.lock
- Replace DjangoCMS picture plugin by our simple picture plugin: only one
field to upload the image, all attributes that control how the image is
resized, cropped and displayed are now in the code,
- In the sandbox project, configure Django Filer to serve private files,
- Create a user group for each course and give it the permission to manage
pages below the course (snapshots and course runs),
- Create a folder in Django Filer for each organization and for each course,
- When a new course is created for an organization, automatically associate
permissions to organization admins (as defined in settings or with sensible
defaults),
- Configure permission checks on page creations via the CMS wizard,
- Automatically create a page role and associate admin permissions when a new
organization …
=> ⬆️(core) upgrade to richie 1.0.0-beta.9

CHANGELOG.md, src/backend/funmooc/settings.py
The `CDN_DOMAIN` setting is empty (at least in `Staging` environment).
We need to set the `CDN_DOMAIN `setting to the same value as the `AWS_CLOUDFRONT_DOMAIN` setting. Let's instantiate it from the environment instead.
=> 🐛(settings) fix CDN_DOMAIN value

CHANGELOG.md, src/frontend/yarn.lock
We learned that versions of fstream below 1.0.12 are unsafe.
Since it is an indirect dependency, we can't update it in our package.json. We can however upgrade our lockfile to ensure we use the safe version.
This will be moot when we get a new version of Richie with updated dependencies but lets us fix the issue right now without needing a new Richie tag.
=> Update fstream to safe version

CHANGELOG.md, src/backend/funmooc/settings.py
The `X_FRAME_OPTIONS` setting should be set to `SAMEORIGIN` to allow DjangoCMS admin frames display; this requires to ignore a system check.
This is a backport from https://github.com/openfun/richie/pull/719
=> 🔧(settings) configure X_FRAME_OPTIONS

CHANGELOG.md, Makefile, requirements/base.txt, src/backend/funmooc/settings.py, src/frontend/package.json, src/frontend/yarn.lock
We are a bit late on the party: we need to upgrade to the latest Richie release.
=> Upgrade richie to 1.4.1

CHANGELOG.md, requirements/base.txt, src/frontend/package.json, src/frontend/yarn.lock
- Add a section "What you will learn" to the course page.
- Fix language confusion when getting objects that are related to a course via a plugin (organizations, categories and persons),
- Use empty image alt text & no link title text for course glimpses to comply with accessibility standards (existing alts & titles were redundant).
- Fix an issue that caused inconsistent UI and broken search results when selecting a suggestion in course search.
=> ⬆️(core) upgrade to Richie 1.5.0

CHANGELOG.md, src/frontend/package.json, src/frontend/yarn.lock
Fixes security vulnerabilities as reported by GitHub.
=> ⬆(frontend) update richie-education to 1.5.1

CHANGELOG.md, src/backend/funmooc/core/admin.py
Django filer allows anyone to upload files to a default directory called `unsorted uploads`.
We want to force our users to upload their images to the right folder (on which we have given them upload rights).
[Django Filer](https://github.com/divio/django-filer) does not let us disable the `unsorted uploads` directory, so we use monkey patching to achieve this feature...
=> 💩(permissions) disable unsorted uploads from Django filer

CHANGELOG.md, requirements/base.txt, src/frontend/package.json, src/frontend/yarn.lock
We've upgraded Richie to version 1.8.3.
for more information, see the project's CHANGELOG:
https://github.com/openfun/richie/blob/master/CHANGELOG.md#183---2019-09-03
=> ⬆️(core) upgrade to Richie 1.8.3

CHANGELOG.md, src/backend/funmooc/gimporter/import_scripts/courses.py, src/backend/funmooc/gimporter/import_scripts/organizations.py
After importing objects from a Google sheet, we must create the related roles and permissions.
Add calls to the existing helper methods for each organization and each course that are being created by the Google sheet importer.
=> ✨(gimporter) create permissions on organizations and courses

CHANGELOG.md, requirements/base.txt, src/backend/funmooc/settings.py, src/frontend/package.json, src/frontend/yarn.lock
We've upgraded Richie to version 1.9.1.
for more information, see the project's CHANGELOG:
https://github.com/openfun/richie/blob/master/CHANGELOG.md#191---2019-09-20
=> ⬆️(core) upgrade to Richie 1.9.1

.circleci/config.yml, CHANGELOG.md, Makefile, bin/pytest, src/backend/funmooc/base/tests/test_settings.py, src/backend/funmooc/settings.py
The DRF API calls were responding with a 403 status code for anonymous users, and were working for authenticated users. This was due to a Basic Auth fallback option in the default configuration of DRF's authentication backends.
For an anonymous user:
- The first authentication backend in the list of DRF's default backends (Django session authentication) does not try to authenticate because it does not see any cookie,
- The second backend (Basic Authentication) tries to authenticate because it sees an Authentication header. But this header is coming from the Nginx htaccess (and is not known by Django), so the authentication fails with a 403.
Removing the Basic Authentication backend allows anonymous users to be really considered as anonymous in Django.
- Remove Basic Auth fallback option …
=> Fix search page behind htaccess

CHANGELOG.md, src/frontend/scss/_main.scss, src/frontend/scss/components/templates/richie/large_banner/_large_banner.scss, src/frontend/scss/settings/_colors.scss
In fun-mooc mockup, the background image in hero intro on homepage is
clearly visible without cropping it.
This commit remove transparent white mask over hero background and let
the image take the full size on large screens.
=> 💄(large_banner) adjust image background size for hero-intro variant

src/aws/cloudfront.tf, src/aws/variables.tf, src/backend/funmooc/settings.py
Static files could not be served via CloudFront. They were blocked by htaccess without any possibility to login because `Authorization` headers were not forwarded by CloudFront.
Forward the `Authorization` header.
=> Let CloudFront forward the Authorization headers to make it work when htaccess is activated

.circleci/config.yml, .circleci/src/workflows/site-factory.yml
Builds are all failing on the master branch.
The circleci configuration on master and tags (that are applied to the master branch) will always be different from what is being generated by an update command... because by definition changes are
computed as compared to the master branch.
Skip checking the circleci configuration on the master branch and on tags.
=> 🐛(circleci) skip check circleci configuration on master and tags

.circleci/config.yml, .circleci/src/workflows/site_jobs.yml.tpl
The job that checks if the CHANGELOG file is modified  is for pull requests. When we tag the master branch, the CHANGELOG file will never be modified.
Stop running the `check-changelog` job on builds triggered by a tag.
=> 🐛(circleci) remove check changelog job for tag builds

.circleci/config.yml, sites/demo/CHANGELOG.md, sites/demo/requirements/base.txt
We normally don't include factory-boy in production images but richie demo is a special image that needs to generate the demo site.
I added factory-boy in the base.txt requirements file.
=> 🐛(demo) add missing factory-boy dependency to demo

.circleci/config.yml, Makefile, docker-compose.yml
When working on several sites in parallel, we want to be able to switch site without losing the database or media files. 
This can be done by mounting data directories specific to each site.
Switching site can now be done by running:
```bash
$ make stop
$ . bin/activate
$ make run
```
=> ✨(dockercompose) allow switching site without losing data

Makefile
When bootstrapping the project for the first time, the data directory is absent and the reset rule should not fail.
Add `|| exit 0` after the reset rule to ensure it does not fail when the `/data` directory is absent.
=> 🐛(Makefile) fix resetting data folder when absent

.circleci/config.yml, Makefile
I want to bootstrap richie by following the **Getting started** instructions from the README.
The `make bootstrap` command failed with the following error (during the `make run` step) : 
```
Starting richie-site-factory_app-dev_1 ... done
2020/07/15 11:21:44 Waiting for: tcp://db:5432
2020/07/15 11:21:44 Problem with dial: dial tcp: lookup db on 127.0.0.11:53: no such host. Sleeping 1s
2020/07/15 11:21:45 Problem with dial: dial tcp: lookup db on 127.0.0.11:53: no such host. Sleeping 1s
[...]
2020/07/15 11:22:43 Problem with dial: dial tcp: lookup db on 127.0.0.11:53: no such host. Sleeping 1s
2020/07/15 11:22:44 Timeout after 1m0s waiting on dependencies to become available: [tcp://db:5432]
make: *** [Makefile:80: run] Error 1
```
After looking at log files, I found that the database …
=> 🐛(Makefile) fix database directory initialization

.circleci/config.yml, sites/cnfpt/aws/config.tfvars
CNFPT refused to create a record for new.mooc.cnfpt.fr and created new-mooc.cnfpt.fr.
Change CloudFront configuration to point to the new domain.
Note: this PR is already deployed to production :wink:
=> 🔧(cnfpt) change cloudfront domain to new-mooc.cnfpt.fr in production

aws/cloudfront.tf, docker-compose.yml
Some static files are called with a query string. It breaks the effect of CORS headers to allow cross domain requests when static files are placed behing a CDN.
Passing the query string to the origin fixes the issue.
=> Fix cross domain requests for static files with a querystring

.circleci/config.yml, .circleci/src/jobs/@backend.yml, Makefile, bin/pytest, docker-compose.yml, sites/cnfpt/CHANGELOG.md, sites/cnfpt/requirements/dev.txt, sites/cnfpt/src/backend/base/admin.py, sites/cnfpt/src/backend/base/cache.py, sites/cnfpt/src/backend/cnfpt/settings.py, sites/demo/CHANGELOG.md, sites/demo/requirements/dev.txt, sites/demo/src/backend/base/admin.py, sites/demo/src/backend/base/cache.py, sites/demo/src/backend/demo/settings.py, sites/funcampus/CHANGELOG.md, sites/funcampus/requirements/dev.txt, sites/funcampus/src/backend/base/admin.py, sites/funcampus/src/backend/base/cache.py, sites/funcampus/src/backend/funcampus/settings.py, sites/funcorporate/CHANGELOG.md, sites/funcorporate/requirements/dev.txt, sites/funcorporate/src/backend/base/admin.py, sites/funcorporate/src/backend/base/cache.py, sites/funcorporate/src/backend/funcorporate/settings.py, sites/funmooc/CHANGELOG.md, sites/funmooc/requirements/dev.txt, sites/funmooc/src/backend/base/admin.py, sites/funmooc/src/backend/base/cache.py, sites/funmooc/src/backend/funmooc/settings.py
We want to improve performances of our sites by enabling content and session cache.
I made a POC with the `cnfpt` site.
When approved, we should do this on all sites.
=> Enable cache with redis-sentinel for all sites

.circleci/config.yml, sites/demo/CHANGELOG.md, sites/demo/src/backend/demo/__init__.py, sites/demo/src/frontend/package.json
- Upgrade richie to 2.0.0-beta.11
- Enable Django CMS page cache for non-staff users
- Enable cache for content and sessions
- Fix translation overrides by configuring the specific "locale" directory
=> 🔖(chore) bump demo to 2.0.0-beta.11

.circleci/config.yml, Dockerfile, sites/cnfpt/CHANGELOG.md, sites/demo/CHANGELOG.md, sites/funcampus/CHANGELOG.md, sites/funcampus/src/backend/funcampus/settings.py, sites/funcampus/src/backend/locale/fr/LC_MESSAGES/django.po, sites/funcampus/src/backend/templates/richie/base.html, sites/funcampus/src/backend/templates/social-networks/blogpost-badges.html, sites/funcampus/src/backend/templates/social-networks/course-badges.html, sites/funcampus/src/backend/templates/social-networks/footer-badges.html, sites/funcorporate/CHANGELOG.md, sites/funcorporate/src/backend/funcorporate/settings.py, sites/funcorporate/src/backend/locale/en/LC_MESSAGES/django.po, sites/funcorporate/src/backend/locale/fr/LC_MESSAGES/django.po, sites/funcorporate/src/backend/templates/social-networks/blogpost-badges.html, sites/funcorporate/src/backend/templates/social-networks/course-badges.html, sites/funcorporate/src/backend/templates/social-networks/footer-badges.html, sites/funmooc/CHANGELOG.md
We want to customize social networks links and search filters for funcampus and funcorporate.
For the moment, we use the same social network links as for funmooc.
On fun-campus, show only search filters on 4 dimensions of categories.
On fun-corporate, remove search filters related to course sessions that are not present on this site.
Note: I also added i18n compilation in the DockerFile so the translations are available out-of-the-box.
=> Customize social networks and filters for funcampus and funcorporate

.circleci/config.yml, sites/demo/CHANGELOG.md, sites/demo/src/backend/demo/__init__.py, sites/demo/src/backend/demo/settings.py, sites/demo/src/frontend/package.json
Richie is behind a proxy and the redirect uri computed has a wrong
schema, http instead of https. To force https we must set the setting
SOCIAL_AUTH_REDIRECT_IS_HTTPS to True.
=> set SOCIAL_AUTH_REDIRECT_IS_HTTPS to true in settings

sites/cnfpt/CHANGELOG.md, sites/cnfpt/src/backend/cnfpt/urls.py, sites/demo/CHANGELOG.md, sites/demo/src/backend/demo/__init__.py, sites/demo/src/backend/demo/urls.py, sites/demo/src/frontend/package.json
in urls module we missed to add courses url patterns leading to 404
error once deployed.
=> add missing courses url pattern 

.circleci/config.yml, sites/demo/CHANGELOG.md, sites/demo/src/backend/demo/settings.py, sites/demo/src/backend/demo/social/pipeline/user.py
OpenEdx hawthorn doesn't send in the oauth response if the user is a
superuser, only if he is a staff member. For the demo we decided to set
a user as superuser if he is staff. For this we added a function in the
authentication pipeline executed once we are sure a user exists and
check if he is a staff member. If it's the case then we set the user as
a superuser and we save it.
=> ✨(demo) force user.is_superuser on login when they have is_staff True

.circleci/config.yml, sites/funcampus/aws/config.tfvars
The LMS is now hosted on https://lms.fun-campus.fr and richie on the main domain https://www.fun-campus.fr.
Update AWS CloudFront CDN to point to the new host.
=> 🏗(funcampus) move cms site to www.fun-campus.fr

.circleci/config.yml, bin/tag
Once release commits have landed to master, we need to tag them before pushing the tags to github. This is repetitive and painful
so we should automate it.
Add a `tag` script that:
- looks for commits starting with the 🔖 gitmoji, 
- extracts the site and version from the commit subject
- tags the commit with the corresponding tag of the form {site}-{version}
=> ✨(project) add script to automate tagging

.circleci/config.yml, sites/funcampus/CHANGELOG.md, sites/funcampus/src/backend/templates/courses/cms/fragment_course_glimpse.html, sites/funcampus/src/frontend/js/components/CourseGlimpse/CourseGlimpseFooter.tsx, sites/funcampus/src/frontend/overrides.json, sites/funcampus/src/frontend/package.json
This is no sens to display course state in course glimpse footer on FUN Corporate.
⚠️ This PR depends to [this other one](https://github.com/openfun/richie-site-factory/pull/139) #139
=> ✨(funcampus/frontend) display course duration

.circleci/config.yml, sites/funcorporate/CHANGELOG.md, sites/funcorporate/src/backend/base/tests/test_utils.py, sites/funcorporate/src/backend/base/utils.py, sites/funcorporate/src/backend/funcorporate/settings.py
Max number of plugins in course description needs to be temporarily relaxed because we have legacy content that is very long and that we can't rewrite in the short term.
=> 🔧(funcorporate) customize max number of plugins in course description

aws/s3.tf, aws/variables.tf, sites/demo/CHANGELOG.md, sites/demo/aws/config.tfvars
The demo site is reset every night. This generates a huge amount of media files because new files are added at each reset! 
Adding an expiration lifecycle rule on the bucket is an easy way to keep it under control. I made it generic and configurable for each site.
=> Add media files expiration lifecyle rule for demo site

.circleci/config.yml, .circleci/src/jobs/@frontend.yml, .gitignore, Dockerfile, Makefile, sites/cnfpt/src/frontend/package.json, sites/cnfpt/src/frontend/yarn.lock, sites/demo/src/frontend/package.json, sites/demo/src/frontend/yarn.lock, sites/funcampus/src/frontend/package.json, sites/funcampus/src/frontend/yarn.lock, sites/funcorporate/src/frontend/package.json, sites/funcorporate/src/frontend/yarn.lock, sites/funmooc/src/frontend/package.json, sites/funmooc/src/frontend/yarn.lock
node-sass and libsass have been officially deprecated. The [blog post](https://sass-lang.com/blog/libsass-is-deprecated) which announces it recommended to use `dart-sass` instead.
So we switch to the pure Javascript implementation of `dart-sass`.
https://www.npmjs.com/package/sass
**⚠ Requires next richie-education release.**
=> ➕(sass) replace node-sass by sass

.circleci/config.yml, bin/release
`head -n -1` did not work on Mac OS so it is impossible to commit automatically changes.
=> 🚨(bin/release) should_commit does not work on Mac OS

.circleci/config.yml, sites/cnfpt/CHANGELOG.md, sites/cnfpt/src/backend/base/admin.py, sites/funcampus/CHANGELOG.md, sites/funcampus/src/backend/base/admin.py, sites/funcorporate/CHANGELOG.md, sites/funcorporate/src/backend/base/admin.py, sites/funmooc/CHANGELOG.md, sites/funmooc/src/backend/base/admin.py
Upload files in unsorted folder is forbidden but the error is currently unclear.
=> 🚸(admin) returns a 403 response when upload in unsorted folder

.circleci/config.yml, sites/cnfpt/CHANGELOG.md, sites/cnfpt/requirements/base.txt, sites/demo/CHANGELOG.md, sites/demo/requirements/base.txt, sites/demo/src/frontend/yarn.lock, sites/funcampus/CHANGELOG.md, sites/funcampus/requirements/base.txt, sites/funcorporate/CHANGELOG.md, sites/funcorporate/requirements/base.txt, sites/funcorporate/src/frontend/yarn.lock, sites/funmooc/CHANGELOG.md, sites/funmooc/requirements/base.txt, sites/funmooc/src/frontend/yarn.lock
Since djangocms-admin-style 2.0.2 is released, admin interface issue has been fixed.
https://github.com/django-cms/djangocms-admin-style/blob/master/CHANGELOG.rst
=> ⬆️(all) unpin django to 3.1.1

.circleci/config.yml, .circleci/src/jobs/@backend.yml, Makefile, sites/cnfpt/CHANGELOG.md, sites/cnfpt/src/backend/base/cache.py, sites/cnfpt/src/backend/base/tests/test_cache.py, sites/cnfpt/src/backend/base/utils.py, sites/cnfpt/src/backend/cnfpt/settings.py, sites/demo/CHANGELOG.md, sites/demo/src/backend/base/cache.py, sites/demo/src/backend/base/tests/test_cache.py, sites/demo/src/backend/base/utils.py, sites/demo/src/backend/demo/settings.py, sites/funcampus/CHANGELOG.md, sites/funcampus/src/backend/base/cache.py, sites/funcampus/src/backend/base/tests/test_cache.py, sites/funcampus/src/backend/base/utils.py, sites/funcampus/src/backend/funcampus/settings.py, sites/funcorporate/CHANGELOG.md, sites/funcorporate/src/backend/base/cache.py, sites/funcorporate/src/backend/base/tests/test_cache.py, sites/funcorporate/src/backend/funcorporate/settings.py, sites/funmooc/CHANGELOG.md, sites/funmooc/src/backend/base/cache.py, sites/funmooc/src/backend/base/tests/test_cache.py, sites/funmooc/src/backend/base/utils.py, sites/funmooc/src/backend/funmooc/settings.py
When Redis cache is out of service, an exception is catched and the platform is down which is awkward.
=> Fallback cache when redis cache is down

Dockerfile, sites/cnfpt/CHANGELOG.md, sites/cnfpt/src/backend/cnfpt/settings.py, sites/demo/CHANGELOG.md, sites/demo/src/backend/demo/settings.py, sites/funcampus/CHANGELOG.md, sites/funcampus/src/backend/funcampus/settings.py, sites/funcorporate/CHANGELOG.md, sites/funcorporate/src/backend/funcorporate/settings.py, sites/funmooc/CHANGELOG.md, sites/funmooc/src/backend/funmooc/settings.py
Upgrade our Django CMS fork to tag [fun-3.8.xr1](https://github.com/jbpenrath/django-cms/tree/fun-3.8.xr1) to add control of page tree node
foldability. Set `CMS_PAGETREE_DESCENDANTS_LIMIT` to 30. If a pagetree node has
more than 30 children, user will not be able to unfold it.
=> 🚸(all) prevent a pagetree node to be unfoldable

.circleci/config.yml, sites/cnfpt/src/backend/cnfpt/settings.py, sites/demo/src/backend/demo/settings.py, sites/funcampus/src/backend/funcampus/settings.py, sites/funcorporate/src/backend/funcorporate/settings.py, sites/funmooc/CHANGELOG.md, sites/funmooc/src/backend/base/tests/test_views.py, sites/funmooc/src/backend/base/urls.py, sites/funmooc/src/backend/base/views.py, sites/funmooc/src/backend/funmooc/settings.py, sites/funmooc/src/backend/funmooc/urls.py
We don't want to lose all the traffic currently directed to course syllabus on OpenEdX. 
Add a view that catches these urls and tries to redirect them to the corresponding course, the corresponding university or as a last resort to the search page.
=> Add redirects from openedx routes

sites/cnfpt/CHANGELOG.md, sites/cnfpt/src/backend/cnfpt/urls.py, sites/cnfpt/src/frontend/scss/_main.scss, sites/demo/CHANGELOG.md, sites/demo/src/backend/demo/urls.py, sites/demo/src/frontend/scss/_main.scss, sites/funcampus/CHANGELOG.md, sites/funcampus/src/backend/funcampus/urls.py, sites/funcampus/src/frontend/scss/_main.scss, sites/funcorporate/CHANGELOG.md, sites/funcorporate/src/backend/funcorporate/urls.py, sites/funcorporate/src/frontend/scss/_main.scss, sites/funmooc/CHANGELOG.md, sites/funmooc/src/backend/funmooc/urls.py, sites/funmooc/src/frontend/scss/_main.scss
Default error pages are ugly. In Richie we created custom error templates in line with our styleguides.
=> 🚸(global) use custom views to handle errors

.circleci/config.yml, sites/funmooc/CHANGELOG.md, sites/funmooc/src/backend/base/context_processors.py, sites/funmooc/src/backend/base/static/funmooc/js/tarteaucitron.js, sites/funmooc/src/backend/base/static/funmooc/js/xiti.js, sites/funmooc/src/backend/base/tests/test_context_processors.py, sites/funmooc/src/backend/funmooc/settings.py, sites/funmooc/src/backend/templates/richie/base.html, sites/funmooc/src/frontend/package.json, sites/funmooc/src/frontend/scss/_main.scss, sites/funmooc/src/frontend/scss/components/libs/_tarteaucitron.scss, sites/funmooc/src/frontend/scss/settings/_colors.scss, sites/funmooc/src/frontend/yarn.lock
We would like to be able to get some analytics data from our visitors on FUN Mooc CMS.
We also need to compute a `level2` attribute from an immutable key to identify the root of the current page.
Furthermore, we also need to specify organization if there is one related to the current page. In this way, we will be able to give access to a customized (and restricted) analytics dashboard for each organizations.
=> 📈(funmooc) enable xiti tracking

.circleci/config.yml, .circleci/src/jobs/@backend.yml, Makefile, sites/funmooc/CHANGELOG.md, sites/funmooc/requirements/dev.txt, sites/funmooc/src/backend/base/tests/test_templates.py, sites/funmooc/src/backend/locale/fr/LC_MESSAGES/django.po, sites/funmooc/src/backend/templates/courses/cms/course_detail.html, sites/funmooc/src/frontend/scss/_main.scss, sites/funmooc/src/frontend/scss/components/templates/courses/cms/_course_detail.scss
Since we made the video teaser bigger on the course detail page header, the course run enrollment button was pushed below the fold. We want to feature it on top of the page.
Split open course runs in 2: 
- the first one is displayed in the page's header
- the remaining ones are displayed in the side column
- Appropriate notices are displayed when there is only one open course run or when there are no open course runs at all
=> ✨(funmooc) display first open course run in course detail top header

.circleci/config.yml, sites/funmooc/CHANGELOG.md, sites/funmooc/src/frontend/scss/_main.scss
The stylesheet for the new LTI consumer plugin was missing resulting in a transparent background for example. 
This import was forgotten because it was not mentionned in upgrade instructions. Add it to the `_main.scss` file.
=> 🐛(styles) import missing stylesheet for LTI consumer plugin

.circleci/config.yml, sites/cnfpt/CHANGELOG.md, sites/cnfpt/src/frontend/scss/_main.scss, sites/demo/CHANGELOG.md, sites/demo/src/frontend/scss/_main.scss, sites/funcampus/CHANGELOG.md, sites/funcampus/src/frontend/scss/_main.scss, sites/funcorporate/CHANGELOG.md, sites/funcorporate/src/frontend/scss/_main.scss
The stylesheet for the new LTI consumer plugin was missing resulting in a transparent background for example. 
This import was forgotten because it was not mentionned in upgrade instructions. Add it to the `_main.scss` file.
This is a follow-up of [this PR](https://github.com/openfun/richie-site-factory/pull/207) that we should have applied on all sites.
=> 🐛(all) import missing stylesheet for LTI consumer plugin

.circleci/config.yml, aws/state.tf, sites/cnfpt/aws/config.tfvars
We are migrating cnfpt preprod environment to a new cluster and its URL changed.
=> 🔧(cnfpt) update cloudfront distribution destination

.circleci/config.yml, sites/funmooc/CHANGELOG.md, sites/funmooc/src/backend/funmooc/settings.py, sites/funmooc/src/backend/locale/fr/LC_MESSAGES/django.po
Our support team requested to rename the "First session" filter to "New course" after some feedback proved that the wording was not clear.
Rename filter in settings and update translation files.
=> 🚸(search) rename "first session" filter to "new course"

.circleci/config.yml, sites/funcampus/aws/config.tfvars
We are migrating funcampus preprod environment to a new cluster and its URL changed.
Update the cloudfront destination URL in terraform
=> 🔧(funcampus) update cloudfront distribution destination

.circleci/config.yml, sites/funmooc/aws/config.tfvars
In order to prepare the release of fun-mooc.fr, we have to update cloudfront
production cloudfront app_domain from new.fun-mooc.fr to www.fun-mooc.fr
=> 🔧(funmooc) update cloudfront production app_domain

sites/funmooc/CHANGELOG.md, sites/funmooc/src/backend/base/static/funmooc/js/xiti.js
In order to improve our marketing analytics, we can enable Xiti tracker unless visitor explicitly refuses to share its navigation information. Until now, we were asking visitor approval to send Xiti hits.
=> 🐛(funmooc) enable xiti by default

.circleci/config.yml, bin/ci, env.d/development, sites/cnfpt/CHANGELOG.md, sites/cnfpt/requirements/base.txt, sites/cnfpt/src/backend/cnfpt/settings.py, sites/cnfpt/src/frontend/package.json, sites/cnfpt/src/frontend/yarn.lock, sites/demo/CHANGELOG.md, sites/demo/requirements/base.txt, sites/demo/src/backend/demo/settings.py, sites/demo/src/frontend/package.json, sites/demo/src/frontend/yarn.lock, sites/funcampus/CHANGELOG.md, sites/funcampus/requirements/base.txt, sites/funcampus/src/frontend/package.json, sites/funcampus/src/frontend/yarn.lock, sites/funcorporate/CHANGELOG.md, sites/funcorporate/requirements/base.txt, sites/funcorporate/src/frontend/package.json, sites/funcorporate/src/frontend/yarn.lock, sites/funmooc/CHANGELOG.md, sites/funmooc/requirements/base.txt, sites/funmooc/src/backend/funmooc/settings.py, sites/funmooc/src/frontend/package.json, sites/funmooc/src/frontend/yarn.lock
Bump all sites to Richie 2.5.0
=> Chore/bump to richie v2.5.0

.circleci/config.yml, sites/funmooc/src/backend/base/tests/test_templates.py
A test failed due to a wrong html parsing. As contents in our tests are in french, we have to manage accentuated entities. To get a pretty string, when using etree.tostring we need first to encode this string in "ISO8859-1" (latin-1) then decode the result in "UTF-8"
This test failed just now, because the error ocurred when we check if the course run's start date is contained in the response.content. In french, august is the only month contaning accentuated characters (août) so this test failed only in August
=> ✅(funmooc) fix template test

.circleci/config.yml, sites/ademe/CHANGELOG.md, sites/ademe/aws/config.tfvars, sites/ademe/src/backend/ademe/settings.py, sites/cnfpt/CHANGELOG.md, sites/cnfpt/src/backend/cnfpt/settings.py, sites/demo/CHANGELOG.md, sites/demo/src/backend/demo/settings.py, sites/funcampus/CHANGELOG.md, sites/funcampus/src/backend/funcampus/settings.py, sites/funcorporate/CHANGELOG.md, sites/funcorporate/src/backend/funcorporate/settings.py, sites/funmooc/CHANGELOG.md, sites/funmooc/src/backend/funmooc/settings.py
Fix minor issues encountered when deploying the Ademe image to preprod and production environments.
While doing these 2 fixes, I noticed that the LTI providers settings had "TEST" in their name which is a copy/pasta fail from Richie's sandbox, so I propose to correct it for all sites.
=> [ademe] Fix LTI settings and domain for CloudFront proxying for deployment

Dockerfile
djangocms-admin-style 3.0.0 has been released and includes fixes we need. So we are now able to remove the use of our forked version of this package.
=> 📌(backend) remove use of forked djangocms-admin-style

.circleci/config.yml, sites/funmooc/CHANGELOG.md, sites/funmooc/src/backend/base/static/funmooc/js/xiti.js, sites/funmooc/src/frontend/js/utils/api/web-analytics/index.ts, sites/funmooc/src/frontend/js/utils/api/web-analytics/xiti.ts, sites/funmooc/src/frontend/overrides.json
Since Richie 2.13.0, we are able to track when a user successfully
enrolls to a course. On FUN Mooc, we have to override the frontend part
to add Xiti support and respect user consent.
So from now, when an enrollment request to a course run succeeded, a `click.action` hit with name `courseEnroll` is sent to xiti. This hit contains a custom property `resource_link`. In this way, from Xiti analytic dashboard we are able to segment clicks by resource_link content (so segment by organization, course or course_run)
=> 📈(funmooc) enable xiti course enrollment analytics
