openfun/richie-site-factory

.circleci/config.yml, .gitignore, Dockerfile, Makefile, README.md, bin/manage, bin/state, bin/terraform, docker-compose.yml, docs/aws.md, env.d/aws.dist, requirements/base.txt, src/aws/cloudfront.tf, src/aws/create_state_bucket/dynamodb.tf, src/aws/create_state_bucket/output.tf, src/aws/create_state_bucket/s3.tf, src/aws/create_state_bucket/state.tf, src/aws/create_state_bucket/variables.tf, src/aws/output.tf, src/aws/s3.tf, src/aws/state.tf, src/aws/variables.tf, src/backend/funmooc/settings.py, src/backend/funmooc/storage.py
We want to serve our static and media files with AWS S3 and CloudFront.
I basically copy/pasted what was done on [Marsha](https://github.com/openfun/marsha) and added a similar backend for Media files.
Some dependencies were missing after we have removed them from Richie master, so I proposed a commit to fix this as well.
=> Serve static and media files with AWS

CHANGELOG.md, Makefile, src/backend/funmooc/settings.py
We've noticed some cosmetic improvements that needed to me fixed.
=> Cosmetic improvements

CHANGELOG.md, requirements/base.txt, src/backend/funmooc/settings.py, src/backend/funmooc/urls.py, src/frontend/package.json, src/frontend/yarn.lock
While upgrading Richie to 1.0.0-beta.9, we forgot to upgrade our settings and urls definitions. In the meantime a new richie release came up, thus we've also switched to it!
=> Upgrade to richie-1.0.0

.circleci/config.yml, CHANGELOG.md, Makefile, requirements/dev.txt, src/backend/funmooc/settings.py, src/backend/funmooc/storage.py, src/backend/funmooc/urls.py, src/backend/setup.cfg
Now that we produce backend code for this project, we need to automate its quality assessment.
=> Add backend linters

CHANGELOG.md, Makefile, requirements/base.txt, src/backend/funmooc/gimporter/import_scripts/categories.py, src/backend/funmooc/gimporter/import_scripts/courses.py, src/backend/funmooc/gimporter/import_scripts/helpers.py, src/backend/funmooc/gimporter/import_scripts/organizations.py, src/backend/funmooc/gimporter/import_scripts/persons.py, src/backend/funmooc/gimporter/management/commands/import_fixtures.py, src/backend/funmooc/settings.py, src/frontend/package.json, src/frontend/yarn.lock
We need to automatically import all pages from the existing https://www.fun-mooc.fr website. 
The data was exported from the old website and imported in a Google Sheet where it was polished and completed manually. It must now be imported in Richie so we use basic scripts to browse through the Google sheet and create each page and plugin.
=> Transfer fixtures from fun mooc

CHANGELOG.md, src/backend/funmooc/gimporter/import_scripts/courses.py, src/backend/funmooc/gimporter/import_scripts/persons.py, src/backend/funmooc/settings.py
The Google sheet importer did not import licences yet.
Licences are imported from a separate Google sheet and linked in each course via their code.
=> ✨(gimporter) add licences to google sheet importer

CHANGELOG.md, src/backend/funmooc/gimporter/import_scripts/blogposts.py, src/backend/funmooc/gimporter/import_scripts/courses.py, src/backend/funmooc/gimporter/import_scripts/helpers.py, src/backend/funmooc/gimporter/management/commands/import_fixtures.py
We want to import old news articles from https://www.fun-mooc.fr.
=> Import blogposts from old funmooc site via gimporter

CHANGELOG.md, requirements/base.txt, src/frontend/package.json, src/frontend/yarn.lock
We've upgraded Richie to version 1.10.0.
for more information, see the project's CHANGELOG:
https://github.com/openfun/richie/blob/master/CHANGELOG.md#1100---2019-10-08
=> ⬆️(project) Upgrade richie to 1.10.0

.circleci/config.yml, .gitignore, aws/cloudfront.tf, aws/create_state_bucket/dynamodb.tf, aws/create_state_bucket/s3.tf, aws/create_state_bucket/state.tf, aws/create_state_bucket/variables.tf, aws/output.tf, aws/s3.tf, aws/state.tf, aws/variables.tf, bin/state, bin/terraform, docker-compose.yml, sites/cnfpt/aws/config.tfvars, sites/demo/aws/config.tfvars, sites/funcorporate/aws/config.tfvars, sites/funmooc/aws/config.tfvars
Trying to deploy all sites to AWS, I had to make some adjustments.
=> Finalize terraform project to deploy to aws

.circleci/config.yml, .gitignore, Makefile, sites/cnfpt/CHANGELOG.md, sites/cnfpt/src/backend/cnfpt/settings.py, sites/cnfpt/src/backend/locale/fr/LC_MESSAGES/django.po, sites/cnfpt/src/backend/templates/richie/base.html, sites/cnfpt/src/backend/templates/social-networks/blogpost-badges.html, sites/cnfpt/src/backend/templates/social-networks/course-badges.html, sites/cnfpt/src/backend/templates/social-networks/footer-badges.html, sites/demo/CHANGELOG.md, sites/demo/src/backend/demo/settings.py, sites/funcampus/CHANGELOG.md, sites/funcampus/src/backend/funcampus/settings.py, sites/funcorporate/CHANGELOG.md, sites/funcorporate/src/backend/funcorporate/settings.py, sites/funmooc/CHANGELOG.md, sites/funmooc/src/backend/funmooc/settings.py
This PR proposes some changes to the CNFPT site as per their requests:
- Fix translation overrides for all projects
- Customize french version of the footer title
- Customize social network links for CNFPT
- Deactivate the english version of the site
=> Customize footer and social network links for cnfpt + deactivate english

.circleci/config.yml, sites/demo/CHANGELOG.md, sites/demo/requirements/base.txt, sites/demo/src/backend/demo/__init__.py, sites/demo/src/backend/demo/settings.py, sites/demo/src/frontend/package.json, sites/demo/src/frontend/scss/_main.scss, sites/demo/src/frontend/yarn.lock
- Upgrade richie to 2.0.0-beta.14 (LMS bridge and language dropdown)
- Set public english language
- Add i18n messages compilation in the DockerFile so translations are ready
=> bump demo to 2.0.0-beta.14

sites/demo/CHANGELOG.md, sites/demo/src/backend/demo/__init__.py, sites/demo/src/backend/demo/urls.py, sites/demo/src/frontend/package.json
Social urls were not declared in urls module. We must import them in
order to use SSO.
=> Fix demo urls

.circleci/config.yml, sites/demo/CHANGELOG.md, sites/demo/src/backend/demo/__init__.py, sites/demo/src/backend/demo/settings.py, sites/demo/src/frontend/package.json
SSO config is missing in settings, this PR add them and publish a new release
=> LMS bridge for the Demo website

.circleci/config.yml, sites/cnfpt/CHANGELOG.md, sites/cnfpt/requirements/base.txt, sites/cnfpt/src/frontend/package.json, sites/cnfpt/src/frontend/scss/components/templates/richie/large_banner/_large_banner.scss, sites/cnfpt/src/frontend/yarn.lock
Support team reported color issue on the home page large banner search title.
=> Cnfpt change large banner search title color

.circleci/config.yml, sites/cnfpt/CHANGELOG.md, sites/cnfpt/src/frontend/yarn.lock, sites/demo/CHANGELOG.md, sites/demo/src/frontend/yarn.lock
Dependabot tries to upgrade elliptic and lodash on demo ans cnfpt sites. This PR aggregates all the commits made by dependabot
=> Bump elliptic and lodash

.circleci/config.yml, sites/demo/CHANGELOG.md, sites/demo/src/backend/demo/__init__.py, sites/demo/src/backend/demo/settings.py, sites/demo/src/frontend/package.json
We want to map is_staff and is_superuser to create user with this
attributes when a user is created using SSO.
=> define missing EDX_USER_PROFILE_TO_DJANGO settings 

.circleci/config.yml, sites/funcorporate/CHANGELOG.md, sites/funcorporate/src/frontend/scss/_main.scss, sites/funcorporate/src/frontend/scss/components/_subheader.scss, sites/funcorporate/src/frontend/scss/settings/_colors.scss
On funcorporate, there was a difference between mockups and integration on course detail page; category badges layout was not correct.
=> 💄(funcorporate) fix course category badge layout

.circleci/config.yml, sites/funcorporate/CHANGELOG.md, sites/funcorporate/src/backend/funcorporate/settings.py
The English version of the site is not yet ready so we should stop publishing it. 
Set the english language as not public.
This will automatically hide the language selector as there will only be 1 public language left.
=> 🐛(funcorporate) hide english version of the site until it is ready

sites/funcorporate/CHANGELOG.md, sites/funcorporate/src/backend/locale/en/LC_MESSAGES/django.po, sites/funcorporate/src/backend/locale/fr/LC_MESSAGES/django.po, sites/funcorporate/src/backend/templates/richie/base.html
We want to customize the slogan in tne footer of the fun-corporate.fr site.
=> ♻️(funcorporate) customize slogan in footer

.circleci/config.yml, sites/funcorporate/CHANGELOG.md, sites/funcorporate/src/backend/funcorporate/settings.py, sites/funcorporate/src/backend/locale/en/LC_MESSAGES/django.po, sites/funcorporate/src/backend/locale/fr/LC_MESSAGES/django.po, sites/funcorporate/src/backend/templates/richie/base.html
We want to add a "Dashboard" button to the header
=> Add dashboard button to header and open contact form in a new tab

.circleci/config.yml, .circleci/src/workflows/site-factory.yml, sites/funcorporate/CHANGELOG.md, sites/funcorporate/src/backend/templates/courses/cms/fragment_course_glimpse.html, sites/funcorporate/src/frontend/js/components/CourseGlimpse/CourseGlimpseFooter.tsx, sites/funcorporate/src/frontend/overrides.json
It does not make sense to display course state in course glimpse footer on FUN Corporate.
⚠️ This PR depends to [this other one](https://github.com/openfun/richie-site-factory/pull/139) #139
=> ✨(funcorporate/frontend) display course duration

.circleci/config.yml, bin/upgrade, sites/funcorporate/aws/config.tfvars
We moved the richie site to the main domain https://www.fun-corporate.fr. As a result, the CDN must update its origin.
Point CDN to www.fun-corporate.fr
=> Funcorporate proxy cdn to www

.circleci/config.yml, sites/funcampus/CHANGELOG.md, sites/funcampus/src/backend/locale/fr/LC_MESSAGES/django.po, sites/funcampus/src/backend/templates/courses/cms/course_detail.html
Some students are contacting us with requests to privatize a course.
Make it clearer that this button is targeted to teachers only.
=> 🚸(funcampus) clarify the "contact us" call-to-action

.circleci/config.yml, sites/funcorporate/CHANGELOG.md, sites/funcorporate/src/backend/locale/en/LC_MESSAGES/django.po, sites/funcorporate/src/backend/locale/fr/LC_MESSAGES/django.po, sites/funcorporate/src/frontend/i18n/overrides/en-US.json, sites/funcorporate/src/frontend/i18n/overrides/fr-CA.json, sites/funcorporate/src/frontend/i18n/overrides/fr-FR.json
C&P would like to replace course by training on FUN Corporate
**This PR is blocked by #150**
=> 🌐(funcorporate) update translation according feedbacks

.circleci/config.yml, sites/demo/CHANGELOG.md, sites/demo/src/backend/demo/settings.py
As a demo, this site should be in english by default. Generating the demo was broken so this is also helping us to fix the command without making a new richie release 😉
Set the `LANGUAGE_CODE` setting to "en"
=> 🌐(demo) set default language to english

.circleci/config.yml, sites/cnfpt/CHANGELOG.md, sites/cnfpt/src/backend/cnfpt/settings.py, sites/demo/CHANGELOG.md, sites/demo/src/backend/demo/settings.py, sites/funcampus/CHANGELOG.md, sites/funcampus/src/backend/funcampus/settings.py, sites/funcorporate/CHANGELOG.md, sites/funcorporate/src/backend/funcorporate/settings.py, sites/funmooc/CHANGELOG.md, sites/funmooc/src/backend/funmooc/settings.py
Sentry SDK is misconfigured
When used in settings file where they are defined, properties ENVIRONMENT and
RELEASE return the object signature not the value they should return elsewhere
Fix Sentry configuration #191
=> 🐛(all) sentry dsn is misconfigured

.circleci/config.yml, Dockerfile
We are contributing to django-cms to improve the search page results. We would like to test this new feature quickly on our platforms.
**⚠ This sould be removed as soon as this feature will be officialy released!**
=> 📌(django-cms) use our forked version

.circleci/config.yml, sites/funmooc/CHANGELOG.md, sites/funmooc/src/backend/funmooc/settings.py, sites/funmooc/src/backend/locale/fr/LC_MESSAGES/django.po
A new category has been created on funmooc : "types" containing sub-categories espacially to know if a course is certifying or not.
C&P asks us to add this new category in search filters.
=> ✨(funmooc) add labels categories as search filter

sites/cnfpt/CHANGELOG.md, sites/cnfpt/requirements/base.txt, sites/cnfpt/src/frontend/package.json, sites/cnfpt/src/frontend/yarn.lock, sites/demo/CHANGELOG.md, sites/demo/requirements/base.txt, sites/demo/src/frontend/package.json, sites/demo/src/frontend/yarn.lock, sites/funcampus/CHANGELOG.md, sites/funcampus/requirements/base.txt, sites/funcampus/src/frontend/package.json, sites/funcampus/src/frontend/yarn.lock, sites/funcorporate/CHANGELOG.md, sites/funcorporate/requirements/base.txt, sites/funcorporate/src/frontend/package.json, sites/funcorporate/src/frontend/yarn.lock, sites/funmooc/CHANGELOG.md, sites/funmooc/requirements/base.txt, sites/funmooc/src/frontend/package.json, sites/funmooc/src/frontend/yarn.lock
=> Upgrade to richie v2.3.0

.circleci/config.yml, sites/funcorporate/aws/config.tfvars
We are migrating funcorporate preprod environment to a new cluster and its URL changed.
Update the cloudfront destination URL in terraform
=> 🔧(funcorporate) update cloudfront distribution destination

.circleci/config.yml, README.md
The readme mentions projects running on localhost:8080, while in reality they are running on localhost:8070, as seen in the
docker-compose file.
Change port in the docs.
=> 📝(readme) fix default dev address in README

.circleci/config.yml, sites/ademe/requirements/dev.txt, sites/cnfpt/requirements/dev.txt, sites/demo/requirements/dev.txt, sites/funcampus/requirements/dev.txt, sites/funcorporate/requirements/dev.txt, sites/funmooc/requirements/dev.txt
A click update broke black. This has been fixed in version 22.3.0.
psf/black#2964
=> ⬆️(all) upgrade black to version 22.3.0

.circleci/config.yml, Dockerfile
From Dockerfile, update the link to install django-cms to download our
fork with tag `fun-3.10.0`
=> ⬆️(all) upgrade to django-cms 3.10.0
